CC = g++
CFLAGS = -Wall -pedantic -Werror -Wshadow -Wstrict-aliasing -Wstrict-overflow
SOURCE = ../sources/Pomodoro.cpp ./*.cpp
LINKING = -lncurses
main: $(SOURCE)
	$(CC) $(CFLAGS) $(SOURCE) -o tests $(LINKING)   
